// SPDX-FileCopyrightText: Copyright (c) Stanford University, The Regents of the
// University of California, and others. SPDX-License-Identifier: BSD-3-Clause

/// @file

#include "ActiveStressLandNiederer.h"
#include "active_stress_test_helpers.h"
#include "gtest/gtest.h"

/**
 * @test Run a standalone ActiveStressLandNiederer twitch for 600 updates with
 * @f$\Delta t=1\,\mathrm{ms}@f$, the prescribed calcium and fiber-stretch
 * trajectories, and the multiscale Land 2017 calibration configured below
 * (svMP's model defaults).
 *
 * The trusted reference is generated by driving the original MATLAB
 * @c Land.m implementation (adapted from https://www.cemrg.co.uk/models) 
 * through the MATLAB engine with a manual Forward-Euler integrator that 
 * mirrors @c ActiveStressODE's update rule; it is not generated by svMultiPhysics. 
 * See this [repo](https://github.com/kko27/generate_ref_solution.git) to access the 
 * reference solution generator and model. See @ref ActiveStressLandNiederer 
 * for the model equations and state ordering: states 0-5 are the Land 2017 ODE states 
 * (XB, XW, CaTRPN, XS, ZETAW, ZETAS) and state 6 is the deterministic Frank-Starling 
 * length-dependence factor LFac.
 */
TEST(ActiveStressTrajectory, LandNiederer) {
  ActiveStressLandNiederer::Parameters params;

  ActiveStressTrajectoryConfiguration configuration;
  configuration.final_time = 600.0;
  configuration.time_step = 1.0;
  configuration.reference_csv_filename =
      "active_stress_land_niederer_twitch.csv";

  ActiveStressTrajectoryTest<ActiveStressLandNiederer> trajectory(
      params, configuration);
  trajectory.run();
}
